### ISSUE TITLE
Why can't I reproduce the baseline results in Table 2?

### ISSUE THREAD

**Issue by jayeew** [jianhao2016/GPRGNN#14]
When I try to reproduce the baseline results use your code, I have some problems. eg. GAT.

I have tried lr={0.002, 0.01, 0.05} and wd={0.0, 0.0005} , but the best test acc I got in datasets 'squirrel' is 29.9328 ± 0.8234. In your paper, it is 42.72±0.33. For other models and  heterophily datasets, same things happened.

PS: for GAT & squirrel, all hyperparameters are (hidden=64, dropout=0.5, train_rate=0.6, val_rate=0.2, heads=8, output_heads=1)

**Comment by elichienxD** [comment]
Hi @jayeew,

I just try GAT with squirrel on my end and it works fine, see my screenshot below. I use lr=0.05 and wd=0.0. Could you try again with the same PyG version as I have (screenshot below)?

![image](https://user-images.githubusercontent.com/46387845/164762542-66941803-2667-4f1d-b40d-341f8db44e97.png)

My tested PyG version:
![image](https://user-images.githubusercontent.com/46387845/164762658-7b6639b4-912a-4311-901c-e8597ab9644f.png)

Best,
Eli

**Comment by jayeew** [comment]
Thanks for your reply.
I have made a mistake. For WikipediaNetwork('squirrel' & 'chameleon'), I use everything from "geom_gcn_preprocess=True".

**Comment by elichienxD** [comment]
Hi @jayeew,

I just have time to test more carefully with more method. I have git clone the our current version and achieve the following results using the parameters stated in our paper:
![image](https://user-images.githubusercontent.com/46387845/164873158-5e877bf8-0887-4f86-a865-14a640ab3e4b.png)

My PyG version is 
![image](https://user-images.githubusercontent.com/46387845/164873176-b29cc779-db28-4377-9f9d-ebb3bdbf32af.png)

Please check again with the following steps:
1. Install the PyG version as above.
2. For GCN with Squirrel, I use lr=0.05 with wd=0. For GAT, I use lr=0.05, wd=0 and hidden=8. Note that since we have 8 heads, so it is using 64 total hidden unit for fair comparison.

Best,
Eli

**Comment by jayeew** [comment]
Thank you again. I'm touched by your patient help.
It was my mistake that caused the problem. And I apologize for taking up your valuable time.

Wish you every day happy and scientific research success!
