### ISSUE TITLE
Test Std

### ISSUE THREAD

**Issue by wendioooo** [jianhao2016/GPRGNN#17]
I reproduced the experiment on Texas and Chameleon, however, I found that the test accuracy matched the results in your paper, but the test std could not match your paper. The test std on Texas is 0.61 in your paper, but 3.05 in my experiment. I haven't change any code, but only run the Reproduce_GPRGNN.sh. I'm wondering what may contribute to this difference, could you please answer my question, thanks!

**Comment by elichienxD** [comment]
Hi @wendioooo ,

Thanks for being interested in our work! Note that we report the 95% confidence interval instead of std in Table 2. This is stated in our paper. 
![image](https://user-images.githubusercontent.com/46387845/209211405-cb737bd1-13f7-4d30-9c19-ab89b8118aef.png)

Please let me know if you have any other questions.

Best,
Eli

**Comment by elichienxD** [comment]
Hi @wendioooo ,

Since there seem no follow-up questions, I'll close the issue for now. Feel free to reopen the issue if you still have problems.

Best,
Eli
